; PHP 7.2 NTS — ionCube opcode dumper
[PHP]
extension_dir = "ext"

; ionCube MUST be a zend_extension, loaded BEFORE opcodedump
zend_extension = "ioncube_loader_win_7.2.dll"

; opcodedump extension
extension = php_opcodedump
extension = openssl

memory_limit = -1
max_execution_time = 0
max_input_time = -1

display_errors = On
log_errors = On
error_reporting = E_ALL

